=== muloem/xins/src/dtd/api_1_0.dtd
<!--
 XINS api DTD. This DTD should be added to the api.xml file of the
 project by adding the following lines at the top of the file :
<!DOCTYPE api PUBLIC "-//XINS//DTD XINS API 1.0//EN" "http://xins.sourceforge.net/dtd/api_1_0.dtd">
-->
<!-- @deprecated With the new directory structure impl-java should be removed. -->
<!ELEMENT api (description, function*, type*, resultcode*, environment*, impl-java?)>
<!ATTLIST api
          name       NMTOKEN #REQUIRED
          freeze     NMTOKEN #IMPLIED
          owner      CDATA   #IMPLIED
          rcsversion CDATA   #IMPLIED
          rcsdate    CDATA   #IMPLIED
>
<!ELEMENT description (#PCDATA|em)*>
<!ELEMENT em (#PCDATA)>
<!ELEMENT function EMPTY>
<!ATTLIST function
          name       NMTOKEN #REQUIRED
          freeze     NMTOKEN #IMPLIED
>
<!ELEMENT type EMPTY>
<!ATTLIST type
          name       NMTOKEN #REQUIRED
          freeze     NMTOKEN #IMPLIED
>
<!ELEMENT resultcode EMPTY>
<!ATTLIST resultcode
          name       NMTOKEN #REQUIRED
          freeze     NMTOKEN #IMPLIED
>
<!ELEMENT environment EMPTY>
<!ATTLIST environment
          id         CDATA #REQUIRED
          url        CDATA #REQUIRED
>
<!ELEMENT impl-java (dependency*, instance*, param*)>
<!ATTLIST impl-java
          mapping    CDATA #IMPLIED
>
<!ELEMENT dependency EMPTY>
<!ATTLIST dependency
          dir        CDATA #REQUIRED
          includes   CDATA #IMPLIED
          type       CDATA #IMPLIED
>
<!ELEMENT instance EMPTY>
<!ATTLIST instance
          name        CDATA #REQUIRED
          getter      CDATA #IMPLIED
          class       CDATA #REQUIRED
>
<!ELEMENT param (#PCDATA)>
<!ATTLIST param
          name        CDATA #REQUIRED
>

=== muloem/xins/src/tests/apis/allinone/spec/api.xml
<?xml version="1.0" encoding="US-ASCII"?>
<!DOCTYPE api PUBLIC "-//XINS//DTD XINS API 1.0//EN" "http://xins.sourceforge.net/dtd/api_1_0.dtd">

<api name="allinone" owner="johnd"
rcsversion="$Revision$" rcsdate="$Date$">

	<description>API that uses all the features included in XINS.</description>

	<function name="SimpleTypes"  />
	<function name="DefinedTypes" />
	<function name="ResultCode"   />
	<function name="DataSection"  />
	<function name="DataSection2" freeze="1.1" />
	<function name="DataSection3" />
	<function name="Logdoc"       />
	<function name="ParamCombo"   />

	<type name="Age"               />
	<type name="AgeNameProperties" />
	<type name="IPAddress"         />
	<type name="TextList"          freeze="1.1" />
	<type name="Salutation"        />

	<resultcode name="AlreadySet"    />
	<resultcode name="InvalidNumber" />

</api>
