=== muloem/xins/src/dtd/log_1_0.dtd
<!--
 XINS logdoc DTD. This DTD should be added to all log.xml file
 by adding the following lines at the top of the file :
<!DOCTYPE log PUBLIC "-//XINS//DTD XINS Logdoc 1.0//EN" "http://xins.sourceforge.net/dtd/log_1_0.dtd">
-->
<!ELEMENT log (translation-bundle*, group*)>
<!ATTLIST log
          default-locale       CDATA #IMPLIED
          domain               CDATA #IMPLIED
>
<!ELEMENT translation-bundle EMPTY>
<!ATTLIST translation-bundle
          locale               CDATA #REQUIRED
>
<!ELEMENT group (entry*)>
<!ATTLIST group
          id               CDATA #REQUIRED
          name             CDATA #IMPLIED
>
<!ELEMENT entry (description, param*)>
<!ATTLIST entry
          id               CDATA #REQUIRED
          level            CDATA #IMPLIED
          exception        CDATA #IMPLIED
>
<!ELEMENT description (#PCDATA|em)*>
<!ELEMENT em (#PCDATA)>
<!ELEMENT param EMPTY>
<!ATTLIST param
          name            CDATA #REQUIRED
          type            CDATA #IMPLIED
          nullable        CDATA #IMPLIED
>

=== muloem/xins/src/logdoc/common/log.xml
<?xml version="1.0" encoding="US-ASCII" ?>
<!DOCTYPE log PUBLIC "-//XINS//DTD XINS Logdoc 1.0//EN" "http://www.xins.org/dtd/log_1_0.dtd">
<!--
 -*- mode: Fundamental; tab-width: 4; -*-
 ex:ts=4

 $Id$
-->

<log>
	<translation-bundle locale="en_US" />

	<group id="trace" name="Tracing of constructors, class functions and instance methods">
		<entry id="3000" level="DEBUG">
			<description>Entering constructor.</description>
			<param name="className" type="text" nullable="false" />
			<param name="detail"    type="text" nullable="true" />
		</entry>
		<entry id="3001" level="DEBUG" exception="true">
			<description>Returning from constructor with exception.</description>
			<param name="className" type="text" nullable="false" />
			<param name="detail"    type="text" nullable="true" />
		</entry>
		<entry id="3002" level="DEBUG">
			<description>Returning from constructor successfully.</description>
			<param name="className" type="text" nullable="false" />
			<param name="detail"    type="text" nullable="true" />
		</entry>
		<entry id="3003" level="DEBUG">
			<description>Entering method.</description>
			<param name="className"  type="text" nullable="false" />
			<param name="methodName" type="text" nullable="false" />
			<param name="detail"     type="text" nullable="true" />
		</entry>
		<entry id="3004" level="DEBUG" exception="true">
			<description>Returning from method with exception.</description>
			<param name="className"  type="text" nullable="false" />
			<param name="methodName" type="text" nullable="false" />
			<param name="detail"     type="text" nullable="true" />
		</entry>
		<entry id="3005" level="DEBUG">
			<description>Returning from method successfully.</description>
			<param name="className"  type="text" nullable="false" />
			<param name="methodName" type="text" nullable="false" />
			<param name="detail"     type="text" nullable="true" />
		</entry>
	</group>

	<group id="lowlevel" name="Low-level generic issues">
		<entry id="3050" level="ERROR">
			<description>Programming error detected.</description>
			<param name="className"  type="text" nullable="false" />
			<param name="methodName" type="text" nullable="false" />
			<param name="detail"     type="text" nullable="true" />
		</entry>
		<entry id="3051" level="ERROR" exception="true">
			<description>Ignoring exception.</description>
			<param name="exceptionClass"   type="text" nullable="false" />
			<param name="exceptionMessage" type="text" nullable="true"  />
			<param name="description"      type="text" nullable="true"  />
		</entry>
	</group>

	<group id="http" name="HTTP-related">
		<entry id="3100" level="INFO">
			<description>Calling HTTP service.</description>
			<param name="url"	       type="text"  nullable="false" />
			<param name="totalTimeOut"      type="int32" nullable="false" />
			<param name="connectionTimeOut" type="int32" nullable="false" />
			<param name="socketTimeOut"     type="int32" nullable="false" />
		</entry>
		<entry id="3101" level="NOTICE">
			<description>Connection refused while calling HTTP service.</description>
			<param name="url" type="text" nullable="false" />
		</entry>
		<entry id="3102" level="NOTICE">
			<description>Connection time-out while calling HTTP service.</description>
			<param name="url"     type="text"  nullable="false" />
			<param name="timeOut" type="int32" nullable="false" />
		</entry>
		<entry id="3103" level="NOTICE">
			<description>Socket time-out while calling HTTP service.</description>
			<param name="url"     type="text"  nullable="false" />
			<param name="timeOut" type="int32" nullable="false" />
		</entry>
		<entry id="3104" level="NOTICE">
			<description>Total call time-out while calling HTTP service.</description>
			<param name="url"     type="text"  nullable="false" />
			<param name="timeOut" type="int32" nullable="false" />
		</entry>
		<entry id="3105" level="INFO">
			<description>HTTP result received, status code is considered acceptable.</description>
			<param name="url"  type="text"  nullable="false" />
			<param name="code" type="int32" nullable="false" />
		</entry>
		<entry id="3106" level="INFO">
			<description>HTTP result received, status code is considered unacceptable.</description>
			<param name="url"  type="text"  nullable="false" />
			<param name="code" type="int32" nullable="false" />
		</entry>
		<entry id="3107" level="NOTICE" exception="true">
			<description>Unrecognized I/O error while calling HTTP service.</description>
			<param name="url" type="text"  nullable="false" />
		</entry>
		<entry id="3108" level="NOTICE" exception="true">
			<description>Unexpected exception while calling HTTP service.</description>
			<param name="url" type="text"  nullable="false" />
		</entry>
		<entry id="3109" level="NOTICE" exception="false">
			<description>Unknown host error while calling HTTP service.</description>
			<param name="url" type="text"  nullable="false" />
		</entry>
	</group>

	<group id="io" name="General I/O">
		<entry id="3200" level="INFO">
			<description>Starting file watch thread.</description>
			<param name="file"     type="text"  nullable="false" />
			<param name="interval" type="int32" nullable="false" />
		</entry>
		<entry id="3201" level="INFO">
			<description>Changing file watch interval.</description>
			<param name="file"	type="text"  nullable="false" />
			<param name="oldInterval" type="int32" nullable="false" />
			<param name="newInterval" type="int32" nullable="false" />
		</entry>
		<entry id="3202" level="INFO">
			<description>Stopping file watch thread.</description>
			<param name="file" nullable="false" />
		</entry>
	</group>

	<group id="text" name="Text">
		<entry id="3250" level="DEBUG">
			<description>Increasing capacity of FastStringBuffer instance.</description>
			<param name="currentCapacity" type="int32" nullable="false" />
			<param name="newCapacity"     type="int32" nullable="false" />
		</entry>
	</group>

	<group id="service" name="Service calling framework">
		<entry id="3300" level="ERROR" exception="true">
			<description>URL is malformed.</description>
			<param name="url" type="text" nullable="false" />
		</entry>
		<entry id="3301" level="DEBUG">
			<description>Call to a specific target succeeded.</description>
			<param name="url" type="text" nullable="false" />
		</entry>
		<entry id="3302" level="WARNING">
			<description>Call to a specific target failed.</description>
			<param name="url" type="text" nullable="false" />
		</entry>
		<entry id="3303" level="ERROR">
			<description>Call completely failed.</description>
			<!-- TODO: Include call (request) ID ? -->
		</entry>
		<entry id="3304" level="INFO">
			<description>No more targets and no fail-over</description>
		</entry>
		<entry id="3305" level="INFO">
			<description>No more targets, but fail-over would be allowed</description>
		</entry>
		<entry id="3306" level="INFO">
			<description>More targets available, but fail-over is not allowed</description>
		</entry>
		<entry id="3307" level="INFO">
			<description>More targets available and fail-over is allowed</description>
		</entry>
	</group>

	<group id="collections" name="Generic collection classes" />

	<group id="collections.expiry" name="Expiry-related collection classes">
		<entry id="3400" level="DEBUG">
			<description>Tick processed.</description>
			<param name="folderName" type="text"  nullable="false" />
			<param name="expired"    type="int32" nullable="false" />
			<param name="remaining"  type="int32" nullable="false" />
		</entry>
		<entry id="3401" level="DEBUG">
			<description>Associating expiry folder with expiry stategy thread.</description>
			<param name="folder"   type="text" nullable="false" />
			<param name="strategy" type="text" nullable="false" />
		</entry>
		<entry id="3402" level="DEBUG">
			<description>Expiry strategy thread started.</description>
			<param name="name" type="text" nullable="false" />
		</entry>
		<entry id="3403" level="DEBUG">
			<description>Expiry strategy thread stopped.</description>
			<param name="name" type="text" nullable="false" />
		</entry>
	</group>

	<group id="threads" name="Threading">
		<entry id="3420" level="ERROR">
			<description>Unable to add Thread to Doorman queue due to a time-out.</description>
			<param name="className"	type="text"  nullable="false" />
			<param name="thread"	   type="text"  nullable="false" />
			<param name="maxQueueWaitTime" type="int64" nullable="false" />
		</entry>
	</group>

	<group id="types" name="Types" />
</log>

=== muloem/xins/src/tests/apis/allinone/impl/log.xml
<?xml version="1.0" encoding="US-ASCII"?>
<!DOCTYPE log PUBLIC "-//XINS//DTD XINS Logdoc 1.0//EN" "http://xins.sourceforge.net/dtd/log_1_0.dtd">

<log>

	<translation-bundle locale="en_US" />

	<group id="exampleLogdoc" name="Example">
		<entry id="10000" level="DEBUG">
			<description>Found a number in the input.</description>
			<param name="parameter" />
			<param name="number" nullable="false" type="int32" />
		</entry>
		<entry id="10001" level="ERROR" exception="true">
			<description>The system can not find any number in the given parameter.</description>
		</entry>
		<entry id="10002" level="WARNING">
			<description>Example of warning using a lot of different parameters.</description>
			<param name="odd" nullable="false" type="boolean" />
			<param name="moreThousands" type="boolean" />
			<param name="square" nullable="false" type="int64" />
			<param name="thread" type="serializable" />
			<param name="date" nullable="false" type="object" />
		</entry>
	</group>
</log>

=== muloem/xins/src/logdoc/client/log.xml
<?xml version="1.0" encoding="US-ASCII" ?>
<!DOCTYPE log PUBLIC "-//XINS//DTD XINS Logdoc 1.0//EN" "http://xins.sourceforge.net/dtd/log_1_0.dtd">
<!--
 -*- mode: Fundamental; tab-width: 4; -*-
 ex:ts=4

 $Id$
-->

<log default-locale="en_US" domain="org.xins.server">

	<translation-bundle locale="en_US" />

	<group id="client" name="Client logdoc">
		<entry id="1000" level="ERROR">
			<description>Unable to convert the input from the specified reader to XML.</description>
			<param name="detail" />
		</entry>
		<entry id="1001" level="ERROR">
			<description>Found element with an empty key and empty value.</description>
			<param name="element_name" nullable="false" />
		</entry>
		<entry id="1002" level="ERROR">
			<description>Found element with an empty key.</description>
			<param name="element_name" nullable="false" />
		</entry>
		<entry id="1003" level="ERROR">
			<description>Found element with an attribute but an empty value.</description>
			<param name="element_name" nullable="false" />
			<param name="key_attribute" nullable="false" />
			<param name="key" nullable="false" />
		</entry>
		<entry id="1004" level="DEBUG">
			<description>Found element with an attribute and a value.</description>
			<param name="element_name" />
			<param name="key_attribute" />
			<param name="key" />
			<param name="value" />
		</entry>
		<entry id="1005" level="ERROR">
			<description>Unable to convert the specified character string to XML.</description>
			<param name="detail" />
		</entry>
		<entry id="1006" level="ERROR">
			<description>The returned XML is invalid. The type of the root element is not "result".</description>
			<param name="element_name" nullable="false" />
		</entry>
		<entry id="1007" level="ERROR" exception="true">
			<description>Caught exception while releasing HTTP connection after request failed.</description>
			<param name="class_name" nullable="false" />
		</entry>
		<entry id="1008" level="ERROR">
			<description>Not OK HTTP code.</description>
			<param name="code" type="int32" nullable="false" />
		</entry>
		<entry id="1009" level="ERROR">
			<description>Failed to read the response body.</description>
		</entry>
		<entry id="1010" level="ERROR" exception="true">
			<description>Unexpected exception caught while calling doCall(org.xins.util.service.CallRequest).</description>
			<param name="class_name" nullable="false" />
		</entry>
	</group>

</log>
