=== muloem/xins/src/dtd/translation-bundle_1_0.dtd
<!--
 XINS translation bundle DTD. This DTD should be added to all translation-bundle-xx-XX.xml file
 by adding the following lines at the top of the file :
<!DOCTYPE translation-bundle PUBLIC "-//XINS//DTD XINS Translation Bundle 1.0//EN" "http://xins.sourceforge.net/dtd/translation-bundle_1_0.dtd">
-->
<!ELEMENT translation-bundle (translation*)>
<!ELEMENT translation (#PCDATA|value-of-param)*>
<!ATTLIST translation
          entry       CDATA #REQUIRED
>
<!ELEMENT value-of-param EMPTY>
<!ATTLIST value-of-param
          name        CDATA #REQUIRED
          format      CDATA #IMPLIED
>

=== muloem/xins/src/logdoc/common/translation-bundle-en_US.xml
<?xml version="1.0" encoding="US-ASCII" ?>
<!DOCTYPE translation-bundle PUBLIC "-//XINS//DTD XINS Translation Bundle 1.0//EN" "http://xins.sourceforge.net/dtd/translation-bundle_1_0.dtd">
<!--
 -*- mode: Fundamental; tab-width: 4; -*-
 ex:ts=4

 $Id$
-->

<translation-bundle>
	<translation entry="8000"><value-of-param name="pattern_class" />.matches(java.lang.String,<value-of-param name="pattern_class" />) has thrown an unexpected exception. Assuming the value <value-of-param name="value" format="quoted" /> is invalid.</translation>
	<translation entry="9000"><value-of-param name="folder_name" />: Expired <value-of-param name="to_be_expired_size" /> entries ( <value-of-param name="new_size" /> remaining).</translation>
	<translation entry="9001"><value-of-param name="folder_name" />: Expired 1 entry ( <value-of-param name="new_size" /> remaining).</translation>
	<translation entry="9002">Size of expiry folder dropped to <value-of-param name="new_size" />, adjusted to 0.</translation>
	<translation entry="9003">Created <value-of-param name="strategy" />, time-out duration is <value-of-param name="time_out" /> ms, precision is <value-of-param name="precision" /> ms.</translation>
	<translation entry="9004"><value-of-param name="folder_name" /> associated with <value-of-param name="strategy" />.</translation>
	<translation entry="9005"><value-of-param name="strategy" /> started.</translation>
	<translation entry="9006"><value-of-param name="strategy" /> stopped.</translation>
	<translation entry="9007">I/O error while attempting to close input stream. Ignoring.</translation>
	<translation entry="9008">I/O error while attempting to disconnect. Ignoring.</translation>
	<translation entry="9009">Starting watch thread for file <value-of-param name="file" format="quoted" />.</translation>
	<translation entry="9010">Changing the watch interval for file <value-of-param name="file" format="quoted" /> from <value-of-param name="old_interval" /> to <value-of-param name="new_interval" /> seconds.</translation>
	<translation entry="9011">Stopping watch thread for file <value-of-param name="file" format="quoted" />.</translation>
	<translation entry="9012"><value-of-param name="class_name" />: Failed to generate secure random int, falling back to pseudo-random.</translation>
	<translation entry="9013"><value-of-param name="class_name" />: Failed to generate secure random long, falling back to pseudo-random.</translation>
	<translation entry="9014">URL <value-of-param name="url" format="quoted" /> is malformed.</translation>
	<translation entry="9015">Caught <value-of-param name="exception_name" /> while releasing HTTP connection after request failed. Ignoring this exception so the original exception is not hidden.</translation>
	<translation entry="9016">Authenticated with <value-of-param name="url" />.</translation>
	<translation entry="9017">Authenticated with <value-of-param name="url" /> as <value-of-param name="principal" format="quoted" />.</translation>
	<translation entry="9018">Failed to authenticate with <value-of-param name="url" />.</translation>
	<translation entry="9019">Failed to authenticate with <value-of-param name="url" /> as <value-of-param name="principal" format="quoted" />.</translation>
	<translation entry="9020">Failed to perform search with base <value-of-param name="search_base" format="quoted" />, filter <value-of-param name="filter" format="quoted" />.</translation>
	<translation entry="9021">Performed search with base <value-of-param name="search_base" format="quoted" />, filter <value-of-param name="filter" format="quoted" />.</translation>
	<translation entry="9022">Ignoring exception thrown by NamingEnumeration.close() to avoid hiding earlier exception.</translation>
	<translation entry="9023">Call to <value-of-param name="target" /> succeeded.</translation>
	<translation entry="9024">Call to <value-of-param name="target" /> failed. Reason: <value-of-param name="reason" />.</translation>
	<translation entry="9025">Failed to call any of the targets.</translation>
	<translation entry="9026">Increasing capacity from <value-of-param name="current_capacity" /> to <value-of-param name="new_capacity" />.</translation>
	<translation entry="9027">Constructed <value-of-param name="class_name" />, initial queue size is <value-of-param name="queue_size" />, maximum queue wait time is <value-of-param name="max_queue_size" /> ms, thread synchronization checking is <value-of-param name="strict" />.</translation>
	<translation entry="9028"><value-of-param name="class_name" />: enterAsReader() called for <value-of-param name="reader" />.</translation>
	<translation entry="9029"><value-of-param name="class_name" />: <value-of-param name="reader" /> attempts to enter as a reader while it is already the active writer.</translation>
	<translation entry="9030"><value-of-param name="class_name" />: <value-of-param name="reader" /> attempts to enter as a reader while it is already an active reader.</translation>
	<translation entry="9031"><value-of-param name="class_name" />: enterAsWriter() called for <value-of-param name="writer" />.</translation>
	<translation entry="9032"><value-of-param name="class_name" />: <value-of-param name="writer" /> attempts to enter as a writer but it is already the active writer.</translation>
	<translation entry="9033"><value-of-param name="class_name" />: <value-of-param name="writer" /> attempts to enter as a writer but it is already an active reader.</translation>
	<translation entry="9034"><value-of-param name="class_name" />: leaveAsReader() called for <value-of-param name="reader" />.</translation>
	<translation entry="9035"><value-of-param name="class_name" />: <value-of-param name="reader" /> attempts to leave protected area as reader, but it is not an active reader.</translation>
	<translation entry="9036"><value-of-param name="class_name" />: leaveAsWriter() called for <value-of-param name="writer" />.</translation>
	<translation entry="9037"><value-of-param name="class_name" />: <value-of-param name="writer" /> attempts to leave protected area as writer, but it is not the current writer.</translation>
</translation-bundle>

=== muloem/xins/src/tests/apis/allinone/impl/translation-bundle-en_US.xml
<?xml version="1.0" encoding="US-ASCII"?>
<!DOCTYPE translation-bundle PUBLIC "-//XINS//DTD XINS Translation Bundle 1.0//EN" "http://xins.sourceforge.net/dtd/translation-bundle_1_0.dtd">

<translation-bundle>
	<translation entry="10000">Found the number <value-of-param name="number" /> in the parameter <value-of-param name="parameter" format="quoted" />.</translation>
	<translation entry="10001">The system could not find any number.</translation>
	<translation entry="10002">Odd: <value-of-param name="odd"/>, more than 1000: <value-of-param name="moreThousands"/>, square: <value-of-param name="square"/>, with thread: <value-of-param name="thread" format="quoted"/>, time: <value-of-param name="date"/> .</translation>
</translation-bundle>

=== muloem/xins/src/logdoc/client/translation-bundle-fr_FR.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE translation-bundle PUBLIC "-//XINS//DTD XINS Translation Bundle 1.0//EN" "http://www.xins.org/dtd/translation-bundle_1_0.dtd">
<!--
 -*- mode: Fundamental; tab-width: 4; -*-
 ex:ts=4

 $Id$
-->

<translation-bundle>
	<translation entry="2000">TRACE: Entre dans le constructeur <value-of-param name="className" />. Détail: <value-of-param name="detail" format="quoted" />.</translation>
	<translation entry="2001">TRACE: Quitte le constructeur <value-of-param name="className" /> avec une exception. Détail: <value-of-param name="detail" format="quoted" />.</translation>
	<translation entry="2002">TRACE: Quitte le constructeur <value-of-param name="className" />. Détail: <value-of-param name="detail" format="quoted" />.</translation>
	<translation entry="2003">TRACE: Entre dans la méthode <value-of-param name="methodName" /> de la classe <value-of-param name="className" />. Détail: <value-of-param name="detail" format="quoted" />.</translation>
	<translation entry="2004">TRACE: Quitte la méthode <value-of-param name="methodName" /> de la classe <value-of-param name="className" /> avec une exception. Détail: <value-of-param name="detail" format="quoted" />.</translation>
	<translation entry="2005">TRACE: Quitte la méthode <value-of-param name="methodName" /> de la classe <value-of-param name="className" />. Détail: <value-of-param name="detail" format="quoted" />.</translation>

	<translation entry="2050">Erreur de programmation dans la méthode <value-of-param name="methodName" /> de la classe <value-of-param name="className" />. Détail: <value-of-param name="detail" format="quoted" />.</translation>
	<translation entry="2051">Ignore l'exception <value-of-param name="exceptionClass" /> avec le message <value-of-param name="exceptionMessage" format="quoted" />. Détail: <value-of-param name="description" format="quoted" />.</translation>
	<translation entry="2052">Attrapé une exception non prévu rejeté par <value-of-param name="throwingClass" />.<value-of-param name="throwingMethod" />.</translation>

	<translation entry="2100">Appelle la fonction <value-of-param name="fonction" /> à <value-of-param name="url" /> avec les paramètres <value-of-param name="parameters" />, le time-out total est de <value-of-param name="totalTimeOut" /> ms, le time-out de la connection est de <value-of-param name="connectionTimeOut" /> ms, le time-out de la socket est de <value-of-param name="socketTimeOut" /> ms.</translation>
	<translation entry="2101">Reçu un résultat de XINS réussi en appellant la fonction <value-of-param name="fonction" /> à <value-of-param name="url" /> avec les paramètres <value-of-param name="parameters" />.</translation>
	<translation entry="2102">Erreur lors de l'appel de la fonction <value-of-param name="fonction" /> à <value-of-param name="url" /> avec les paramètres <value-of-param name="parameters" /> en <value-of-param name="duration" /> ms: host inconnu.</translation>
	<translation entry="2103">Erreur lors de l'appel de la fonction <value-of-param name="fonction" /> à <value-of-param name="url" /> avec les paramètres <value-of-param name="parameters" /> en <value-of-param name="duration" /> ms: Connection refusé.</translation>
	<translation entry="2104">Erreur lors de l'appel de la fonction <value-of-param name="fonction" /> à <value-of-param name="url" /> avec les paramètres <value-of-param name="parameters" /> en <value-of-param name="duration" /> ms: Connection time-out.</translation>
	<translation entry="2105">Erreur lors de l'appel de la fonction <value-of-param name="fonction" /> à <value-of-param name="url" /> avec les paramètres <value-of-param name="parameters" /> en <value-of-param name="duration" /> ms: Socket time-out.</translation>
	<translation entry="2106">Erreur lors de l'appel de la fonction <value-of-param name="fonction" /> à <value-of-param name="url" /> avec les paramètres <value-of-param name="parameters" /> en <value-of-param name="duration" /> ms: Total time-out.</translation>
	<translation entry="2108">Erreur lors de l'appel de la fonction <value-of-param name="fonction" /> à <value-of-param name="url" /> avec les paramètres <value-of-param name="parameters" /> en <value-of-param name="duration" /> ms: Reçu HTTP status code inacceptable: <value-of-param name="code" />.</translation>
	<translation entry="2109">Erreur lors de l'appel de la fonction <value-of-param name="fonction" /> à <value-of-param name="url" /> avec les paramètres <value-of-param name="parameters" /> en <value-of-param name="duration" /> ms: Erreur E/S non specifique.</translation>
	<translation entry="2110">Erreur lors de l'appel de la fonction <value-of-param name="fonction" /> à <value-of-param name="url" /> avec les paramètres <value-of-param name="parameters" /> en <value-of-param name="duration" /> ms: Reçu un résultat XINS invalide. Détail: <value-of-param name="detail" /></translation>
	<translation entry="2111">Erreur lors de l'appel de la fonction <value-of-param name="fonction" /> à <value-of-param name="url" /> avec les paramètres <value-of-param name="parameters" /> en <value-of-param name="duration" /> ms: Attrapé une exception imprèvu.</translation>
	<translation entry="2112">Reçu un résultat XINS non réussi (code erreur <value-of-param name="errorCode" />) lors de l'appel de la fonction <value-of-param name="fonction" /> à <value-of-param name="url" /> avec les paramètres <value-of-param name="parameters" />.</translation>
	<translation entry="2113">La requête de l'appel pour la fonction <value-of-param name="fonction" /> avec les paramètres <value-of-param name="parameters" /> à échoué complement après <value-of-param name="duration" /> ms.</translation>

	<translation entry="2200">L'XML retourné est invalide. Le type de l'élément racine est <value-of-param name="localName" format="quoted" /> avec le namespace <value-of-param name="namespaceURI" format="quoted" /> au lieu de "result" sans namespace.</translation>
	<translation entry="2201">Trouvé un paramètre de sortie sans nom ni valeur.</translation>
	<translation entry="2202">Trouvé un paramètre de sortie sans nom. La valeur est <value-of-param name="value" format="quoted" />.</translation>
	<translation entry="2203">Trouvé un paramètre de sortie sans valeur. Le nom est <value-of-param name="name" format="quoted" />.</translation>
	<translation entry="2204">Trouvé un paramètre de sortie <value-of-param name="name" format="quoted" /> avec la valeur <value-of-param name="value" format="quoted" />.</translation>
	<translation entry="2205">Impossible de convertir le caractère spécifié en XML: <value-of-param name="detail" />.</translation>
	<translation entry="2206">Ignore l'élément non reconnu de type <value-of-param name="localName" format="quoted" /> avec le namespace <value-of-param name="namespaceURI" format="quoted" /> à la racine.</translation>
</translation-bundle>

=== muloem/xins/src/tests/apis/allinone/impl/translation-bundle-fr_FR.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE translation-bundle PUBLIC "-//XINS//DTD XINS Translation Bundle 1.0//EN" "http://xins.sourceforge.net/dtd/translation-bundle_1_0.dtd">

<translation-bundle>
	<translation entry="10000">Trouvé le numéro <value-of-param name="number" />
	dans le paramètre <value-of-param name="parameter" format="quoted" />.</translation>
	<translation entry="10001">Le système n'a pas pu trouvé de numéro.</translation>
	<translation entry="10002">Pair: <value-of-param name="odd"/>,
	plus 1000: <value-of-param name="moreThousands"/>, carré: <value-of-param name="square"/>,
	avec le thread: <value-of-param name="thread" format="quoted"/>, le: <value-of-param name="date"/> .</translation>
</translation-bundle>

=== muloem/xins/src/logdoc/client/translation-bundle-en_US.xml
<?xml version="1.0" encoding="US-ASCII" ?>
<!DOCTYPE translation-bundle PUBLIC "-//XINS//DTD XINS Translation Bundle 1.0//EN" "http://xins.sourceforge.net/dtd/translation-bundle_1_0.dtd">
<!--
 -*- mode: Fundamental; tab-width: 4; -*-
 ex:ts=4

 $Id$
-->

<translation-bundle>
	<translation entry="2000">Unable to convert the input from the specified reader to XML<value-of-param name="detail" />.</translation>
	<translation entry="2001">Found &lt;<value-of-param name="element_name" />/&gt; with an empty key and empty value.</translation>
	<translation entry="2002">Found &lt;<value-of-param name="element_name" />/&gt; with an empty key.</translation>
	<translation entry="2003">Found &lt;<value-of-param name="element_name" />/&gt; with <value-of-param name="key_attribute" /> <value-of-param name="key" format="quoted" /> but an empty value.</translation>
	<translation entry="2004">Found &lt;<value-of-param name="element_name" />/&gt; with <value-of-param name="key_attribute" /> <value-of-param name="key" format="quoted" /> and value <value-of-param name="value" format="quoted" />.</translation>
	<translation entry="2005">Unable to convert the specified character string to XML<value-of-param name="detail" />.</translation>
	<translation entry="2006">The returned XML is invalid. The type of the root element is <value-of-param name="element_name" format="quoted" /> instead of "result".</translation>
	<translation entry="2007">Caught <value-of-param name="class_name" /> while releasing HTTP connection after request failed. Ignoring this exception so the original exception is not hidden.</translation>
	<translation entry="2008">HTTP code <value-of-param name="code" />.</translation>
	<translation entry="2009">Failed to read the response body.</translation>
	<translation entry="2010">Unexpected <value-of-param name="class_name" /> caught while calling doCall(org.xins.util.service.CallRequest).</translation>
</translation-bundle>
